# Loops : iterations 

## 1. for loop : iterate over a sequence ( string list tuple...)

In [5]:
print('N')
print('i')
print('m')
print('i')

N
i
m
i


In [6]:
for i in 'Python' :
    print(i)

P
y
t
h
o
n


In [3]:
basket = ['apple','bananas', 'potato', 'broccoli', 'okra','lettuce', 'cheese', 'yogurt', 'milk']

In [7]:
for i in basket :
    print(i)

apple
bananas
potato
broccoli
okra
lettuce
cheese
yogurt
milk


# print all the other elements and in all caps 

In [8]:
basket[ : : 2]

['apple', 'potato', 'okra', 'cheese', 'milk']

In [9]:
for i in [0,2,4,6,8]:
    print(basket[i].upper())

APPLE
POTATO
OKRA
CHEESE
MILK


## print my name 10 times 

In [10]:
for i in [0,1,2,3,4,5,6,7,8,9]:
    print('Nimisha')

Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha


#  range() --> generates a sequence of int values 
## range(stop) --> this will create a range objecct starting from 0 till stop value (excluding stop)
## range(start, stop [, step ]) --> this will create a range object starting from start (included) till stop(excluding)

In [11]:
range(10) # iteration object 

range(0, 10)

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
for i in range(10):
    print('Nimisha')

Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha


In [15]:
for i in range(0 , len(basket), 2):
    print(basket[i].upper())

APPLE
POTATO
OKRA
CHEESE
MILK


In [20]:
range(1,6)

range(1, 6)

## 2. while loop : executes till the time an exxpression is true 

In [25]:
num = 0
while num < 10 :
    print(num, end = '\n')
    num += 1

0
1
2
3
4
5
6
7
8
9


## Compute factorial of any number
### 5! = 5 * 4 * 3 * 2 * 1

In [27]:
num = int(input('Please enter a number :'))
fac = 1
for i in range(num , 0, -1):
    print(fac, '*', i , '=', fac *i)     
    fac *= i
    

Please enter a number : 5


1 * 5 = 5
5 * 4 = 20
20 * 3 = 60
60 * 2 = 120
120 * 1 = 120


In [33]:
num = int(input('Please enter a number :'))
fac2 = 1
while num >=1:
    print(fac2, '*', num , '=', fac2 *num)     
    fac2 *= num
    num -= 1


Please enter a number : 5


1 * 5 = 5
5 * 4 = 20
20 * 3 = 60
60 * 2 = 120
120 * 1 = 120


In [30]:
# a += 1 ==> a = a+1

## check if a number is prime or not 
#### num which is only divisible by 1 and itself 
#### need to check the divisibilty of the number from 2 to num -1

In [37]:
num = int(input('Please enter a number :'))
result = 'Prime'
for i in range(2, num ):
    if num % i == 0 :
        result = 'Non Prime'
print(result)

Please enter a number : 12


Non Prime


In [38]:
i

11

# flow control statements :
## break : terminate the loop 
## continue : skip the remaining steps in the iteration

In [39]:
num = int(input('Please enter a number :'))
result = 'Prime'
for i in range(2, num ):
    if num % i == 0 :
        result = 'Non Prime'
        break
print(result)

Please enter a number : 32


Non Prime


In [40]:
i

2

In [43]:
h = 0
for i in 'Python':
    if i == 'h':
        h = 1
        continue
    print(i)
    

P
y
t
o
n


### for else statement 
#### else block is executed once the loop is finished 
#### else block is not executed if break is encountered

In [44]:
for x in range(6):
    print(x)
else :
    print('finished')
    

0
1
2
3
4
5
finished


In [48]:
for i in range(10):
    print(i)
    if i == 5:
        continue
else :
    print('finished')

0
1
2
3
4
5
6
7
8
9
finished


In [50]:
num = int(input('Pls enter a number : '))
for i in range(2, num):
    if num%i == 0 :
        print('non prime')
        break
else : print('Prime')

Pls enter a number :  37


Prime


In [52]:
numbers = [23,45,98,45,32,66,86,77,53, 45]
# create a new list from the abovve list with only odds

In [53]:
odd_number = []
for i in numbers:
    if i %2 != 0:
        odd_number.append(i)
odd_number

[23, 45, 45, 77, 53, 45]

In [57]:
# odd_number = [<iterable> <loop> <condition>]
odd_number = [i**2 for i in numbers if i%2 !=0]
odd_number

[529, 2025, 2025, 5929, 2809, 2025]

### Ex. Write a code to generate a dictionary that contains (i, i*i) such that i is an number between 1 and n (both included). and then the program should print the dictionary.

In [ ]:
{<key : value> < loop > <condition>}

In [58]:
n = 10
{ i : i**2 for i in range(1,n+1)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [61]:
basket

['apple',
 'bananas',
 'potato',
 'broccoli',
 'okra',
 'lettuce',
 'cheese',
 'yogurt',
 'milk']

In [63]:
ht = [1.50,1.55,1.53,1.52,1.57, 1.58]
wt = [55,57.5,54.6, 56.5,55.7,54.7]

In [66]:
BMI = [round( wt[i]/ ht[i]**2, 2) for i in range(len(wt)) ]

In [67]:
BMI

[24.44, 23.93, 23.32, 24.45, 22.6, 21.91]

In [68]:
BMI = [ round(w/h**2, 2) for w,h in zip(wt,ht)]
BMI

[24.44, 23.93, 23.32, 24.45, 22.6, 21.91]

In [72]:
ht = [1.50,1.55,1.53,1.52,1.57, 1.58]
wt = [55,57.5,54.6, 56.5,55.7]

In [73]:
BMI = [ round(w/h**2, 2) for w,h in zip(wt,ht)]
BMI

[24.44, 23.93, 23.32, 24.45, 22.6]

In [71]:
for i,j in zip(wt, ht) :
    print(i,j)
    

55 1.5
57.5 1.55
54.6 1.53
56.5 1.52
55.7 1.57


In [74]:
### Ex. Write a code to create a list of prime numbers between 2000 and 3000
### Ex. write a code to ccreate a list of first 100 prime numbers

In [75]:
'She sells sea shells on the sea shore' #--> remove vowels --> aeiou 

'She sells sea shells on the sea shore'

In [77]:
n = ''
for i in 'She sells sea shells on the sea shore':
    if i.lower() not in 'aeiou':
        n += i # concatenating 
    print(n)
print(n)

S
Sh
Sh
Sh 
Sh s
Sh s
Sh sl
Sh sll
Sh slls
Sh slls 
Sh slls s
Sh slls s
Sh slls s
Sh slls s 
Sh slls s s
Sh slls s sh
Sh slls s sh
Sh slls s shl
Sh slls s shll
Sh slls s shlls
Sh slls s shlls 
Sh slls s shlls 
Sh slls s shlls n
Sh slls s shlls n 
Sh slls s shlls n t
Sh slls s shlls n th
Sh slls s shlls n th
Sh slls s shlls n th 
Sh slls s shlls n th s
Sh slls s shlls n th s
Sh slls s shlls n th s
Sh slls s shlls n th s 
Sh slls s shlls n th s s
Sh slls s shlls n th s sh
Sh slls s shlls n th s sh
Sh slls s shlls n th s shr
Sh slls s shlls n th s shr
Sh slls s shlls n th s shr


## user defined functions 

# reusable code 
len() #

In [ ]:
# function definition :
def function_name (inputs/arguments) :
    statements 1
    statements 2
    statements 3
    return < expression > # optional
# function call
function_name(required inputs)

In [85]:
def isprime(n):
    for i in range(2, n):
        if n%i == 0 :
            print('non prime')
            break
    else : print('Prime')

In [92]:
isprime(37)

Prime


In [90]:
# scope of variables :
num = 34
num

34

In [98]:
def isprime(n):
    print('n = ',n)
    for i in range(2, num):
        print(num , 'is ', end = '')
        if num%i == 0 :
            print('non prime')
            break
    else : print('Prime')

In [99]:
isprime(45)

n =  45
34 is non prime


In [ ]:
# num is a global variable 

In [96]:
num

34

In [97]:
n

'Sh slls s shlls n th s shr'

## argumments
1. positional vs keyword

In [101]:
# which calculates volume of a sphere or cylinder based on the value passed for h 
def volume (r, h):
    if h :
        vol = 3.14 * h * r ** 2
    else :
        vol = 4/3 * 3.14 * r ** 3
    return vol

In [102]:
volume(2,3)

37.68

In [104]:
# r = 3 and h = 2
volume ( h = 2, r =3 )

56.52

2. required vs default 

In [133]:
def volume2 (r, h = None):
    if h :
        return print(3.14 * h * r ** 2 , 'Cylinder')
    else :
        return print(4/3 * 3.14 * r ** 3, 'Sphere')

In [132]:
volume2(5)

523.3333333333334 Sphere


In [120]:
volume2(5, 2)

(157.0, 'Cylinder')

In [125]:
0 == False

True

In [ ]:
if expression --> true / false 

In [126]:
if h :
    
h =0 --> False
h != 0 --> True 


True

In [127]:
h = None

In [130]:
if not h:
    print('none')

none


In [137]:
def volume(r,h = None):
    global vol
    if h:
        vol = 3.14 * h * r ** 2 
    else :
        vol = 4/3 * 3.14 * r ** 3

In [138]:
volume(2,2)

In [139]:
vol

25.12

In [140]:
r

NameError: name 'r' is not defined

In [141]:
def change(b):
    b.append(12)

In [142]:
change(basket)

In [143]:
basket

['apple',
 'bananas',
 'potato',
 'broccoli',
 'okra',
 'lettuce',
 'cheese',
 'yogurt',
 'milk',
 12]

In [144]:
# lambda function 

In [152]:
new_fun = lambda x,y=2 : pow(x,y)

In [154]:
new_fun(5)

25

In [155]:
# exception 

In [156]:
num = int(input ('Please enter a number'))

Please enter a number 32.2


ValueError: invalid literal for int() with base 10: '32.2'

In [159]:
try :
    num = int(input ('Please enter a number'))
except ValueError:
    print('Wrong fromat')  
except :
    print('other problem')
    

Please enter a number 45.6


Wrong fromat


In [162]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

## module 

In [1]:
import numpy as np

In [166]:
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

## Array : homogenous ordered collection of data in 1 or more dimensions

In [169]:
ht = [1.5, 1.55, 1.53, 1.52, 1.57, 1.58]
wt = [55, 57.5, 54.6, 56.5, 55.7, 56.5]

In [179]:
height = np.array(ht)
weight = np.array(wt)

In [172]:
height

array([1.5 , 1.55, 1.53, 1.52, 1.57, 1.58])

In [174]:
l = [1,2,'apple','cream', 4.3, True]
l

[1, 2, 'apple', 'cream', 4.3, True]

In [175]:
np.array([1,2,'apple','cream', 4.3, True])

array(['1', '2', 'apple', 'cream', '4.3', 'True'], dtype='<U21')

In [176]:
np.array(['1',2, 4.3, True])

array(['1', '2', '4.3', 'True'], dtype='<U4')

In [177]:
np.array([1,2, 4.3, True])

array([1. , 2. , 4.3, 1. ])

In [178]:
np.array(['1',2, 4.3, True], dtype = 'int')

array([1, 2, 4, 1])

In [181]:
ht*2

[1.5, 1.55, 1.53, 1.52, 1.57, 1.58, 1.5, 1.55, 1.53, 1.52, 1.57, 1.58]

In [182]:
height * 2

array([3.  , 3.1 , 3.06, 3.04, 3.14, 3.16])

In [183]:
weight/height**2

array([24.44444444, 23.93340271, 23.32436242, 24.45463989, 22.59726561,
       22.63259093])

In [184]:
arr_1d = np.array([23,12,34,56,43])

In [189]:
print(arr_1d.ndim)
print(arr_1d.size)
print(arr_1d.shape)
print(arr_1d.dtype)

1
5
(5,)
int64


In [2]:
arr_2d = np.array([[23, 45, 64],[42, 36, 44],[58, 31, 10]])

In [3]:
arr_2d

array([[23, 45, 64],
       [42, 36, 44],
       [58, 31, 10]])

In [4]:
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.shape)
print(arr_2d.dtype)

2
9
(3, 3)
int64


In [199]:
np.zeros((2,3), dtype = str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [202]:
np.ones((2,3), dtype = str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [203]:
np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [204]:
np.zeros_like(height)

array([0., 0., 0., 0., 0., 0.])

In [7]:
cost  = np.random.rand(2,3,4)

In [ ]:
source  --> rows 3 sources (2nd dimension)
destination ---> columns 4 destinations (1 st dimension)
routes --> 3rd dimension 2 routes 

In [8]:
cost

array([[[0.14056529, 0.55212021, 0.61607292, 0.58832121],
        [0.35018455, 0.77941065, 0.48000551, 0.25869833],
        [0.47332056, 0.50500532, 0.94049523, 0.59659243]],

       [[0.26351925, 0.21755917, 0.73594273, 0.69324394],
        [0.37534777, 0.09927789, 0.91491166, 0.59500384],
        [0.17636806, 0.97778484, 0.59339082, 0.55094757]]])

In [9]:
# from source 1 to destination 3 via route 0
cost[0, 1, 3]

0.258698326243632

In [211]:
np.random.randint(20,50,(2,3))

array([[46, 33, 42],
       [27, 34, 43]])

In [10]:
?np.empty

Docstring:
empty(shape, dtype=float, order='C')

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the given shape, dtype, and
    order.  Object arrays will be initialized to None.

See Also
--------
empty_like : Return an empty array with shape and type of input.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Notes
-----
`empty`, unlike `zeros`, does not set the array values to ze

In [11]:
np.empty((2,3))

array([[6.90393094e-310, 4.64999541e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [217]:
arr_2d.shape

(3, 3)

In [218]:
arr_2d

array([[23, 45, 64],
       [42, 36, 44],
       [58, 31, 10]])

In [219]:
# reshaping of an array

In [225]:
arr_2d1 = np.random.randint(10,100,(3,6))

In [232]:
arr_2d1.size

18

In [ ]:
2,9 
9,2
6,3
2,3,3
3,2,3
3,3,2
1 , 18
18 , 1

In [238]:
arr_2d1.reshape(2,9)

array([[66, 79],
       [21, 18],
       [51, 51],
       [36, 76],
       [49, 97],
       [48, 15],
       [93, 48],
       [99, 94],
       [41, 63]])

In [234]:
arr_3d = arr_2d1.reshape(2,3,3)
arr_3d

array([[[66, 21, 51],
        [36, 49, 48],
        [93, 99, 41]],

       [[79, 18, 51],
        [76, 97, 15],
        [48, 94, 63]]])

In [235]:
arr_2d1

array([[66, 21, 51, 36, 49, 48],
       [93, 99, 41, 79, 18, 51],
       [76, 97, 15, 48, 94, 63]])

In [236]:
arr_2d1.shape = (2,3,3)

In [237]:
arr_2d1

array([[[66, 21, 51],
        [36, 49, 48],
        [93, 99, 41]],

       [[79, 18, 51],
        [76, 97, 15],
        [48, 94, 63]]])

In [12]:
cost = np.random.rand(2,3,4)

In [13]:
cost

array([[[0.2934952 , 0.32987949, 0.46876308, 0.35529888],
        [0.70816018, 0.6542938 , 0.02790846, 0.26673665],
        [0.15207242, 0.45783458, 0.2780819 , 0.22066457]],

       [[0.64694558, 0.02745838, 0.73761251, 0.90651391],
        [0.33251696, 0.92142119, 0.14581543, 0.10169809],
        [0.67499176, 0.98304022, 0.51147664, 0.86764575]]])

## Array Indexing

In [23]:
np.random.seed(123)
rand_int  = np.random.randint(10,100,(4,5))
rand_int

array([[76, 27, 93, 67, 96],
       [57, 83, 42, 56, 35],
       [93, 88, 46, 90, 78],
       [59, 65, 77, 12, 94]])

In [25]:
print('Original Array\n', rand_int)

Original Array
 [[76 27 93 67 96]
 [57 83 42 56 35]
 [93 88 46 90 78]
 [59 65 77 12 94]]


In [26]:
rand_int[2,2]

46

In [31]:
# for entire row
rand_int[2].shape

(5,)

In [32]:
# for entire column
rand_int[ : , 2].shape

(4,)

In [34]:
np.random.seed(123)
rand_int3d  = np.random.randint(10,100,(2,4,5))
rand_int3d

array([[[76, 27, 93, 67, 96],
        [57, 83, 42, 56, 35],
        [93, 88, 46, 90, 78],
        [59, 65, 77, 12, 94]],

       [[49, 76, 94, 57, 71],
        [58, 17, 62, 95, 37],
        [44, 86, 50, 13, 79],
        [74, 85, 44, 68, 20]]])

In [36]:
rand_int3d[0,2,2]

46

In [37]:
rand_int3d[0]

array([[76, 27, 93, 67, 96],
       [57, 83, 42, 56, 35],
       [93, 88, 46, 90, 78],
       [59, 65, 77, 12, 94]])

In [40]:
rand_int3d[0,2]

array([93, 88, 46, 90, 78])

In [43]:
rand_int3d[:, 2 , :]

array([[93, 88, 46, 90, 78],
       [44, 86, 50, 13, 79]])

In [ ]:
# same no of dimensions as the no. of changing dimensions in indices

In [44]:
rand_int 

array([[76, 27, 93, 67, 96],
       [57, 83, 42, 56, 35],
       [93, 88, 46, 90, 78],
       [59, 65, 77, 12, 94]])

In [ ]:
# as 4 rows 1 column

In [48]:
rand_int[ : , 1 :2].shape

(4, 1)

In [51]:
rand_int[ : , 1 ]

array([27, 83, 88, 65])

In [52]:
rand_int[ 1, :]

array([57, 83, 42, 56, 35])

In [54]:
rand_int[ 1:2 , 1:2 ]

array([[83]])

In [53]:
rand_int[1,1]

83

In [ ]:
# extract a slice ---> list 

In [49]:
l = [2,3,4,5,6]
l[0:1]

[2]

In [50]:
l[0]

2

In [58]:
rand_int

array([[76, 27, 93, 67, 96],
       [57, 83, 42, 56, 35],
       [93, 88, 46, 90, 78],
       [59, 65, 77, 12, 94]])

In [59]:
#rand_int[rows, columns]
rand_int[[2,1,3,1], [0,3,3,1]]

array([93, 56, 12, 83])

In [60]:
rand_int3d

array([[[76, 27, 93, 67, 96],
        [57, 83, 42, 56, 35],
        [93, 88, 46, 90, 78],
        [59, 65, 77, 12, 94]],

       [[49, 76, 94, 57, 71],
        [58, 17, 62, 95, 37],
        [44, 86, 50, 13, 79],
        [74, 85, 44, 68, 20]]])

In [62]:
rand_int3d[[1,0,0,0], [0,1,3,1],[2,3,3,1]]

array([94, 56, 12, 83])

In [68]:
#rand_int3d[ : ,[2,1,3,1], [0,3,3,1]]
rand_int3d[ [0,0,0,0,1,1,1,1] ,[2,1,3,1,2,1,3,1], [0,3,3,1,0,3,3,1]]

array([93, 56, 12, 83, 44, 95, 68, 17])

In [71]:
rand_int3d[ : ,[2,1,3,1], [0,3,3,1]]

array([[93, 56, 12, 83],
       [44, 95, 68, 17]])

In [72]:
ind = np.array([[2,0],[1,3],[3,3],[1,1]])

In [75]:
rand_int[ind]

array([[[93, 88, 46, 90, 78],
        [76, 27, 93, 67, 96]],

       [[57, 83, 42, 56, 35],
        [59, 65, 77, 12, 94]],

       [[59, 65, 77, 12, 94],
        [59, 65, 77, 12, 94]],

       [[57, 83, 42, 56, 35],
        [57, 83, 42, 56, 35]]])

In [77]:
rand_int[rand_int< 50]

array([27, 42, 35, 46, 12])

In [79]:
np.array(range(10,30))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [80]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

## modification in the arrays

In [86]:
print('before Modification\n\n' , rand_int)

rand_int[rand_int< 500] *= 100

print('\nafter Modification\n\n' , rand_int)

before Modification

 [[  76 2700   93   67   96]
 [  57   83 4200   56 3500]
 [  93   88 4600   90   78]
 [  59   65   77 1200   94]]

after Modification

 [[7600 2700 9300 6700 9600]
 [5700 8300 4200 5600 3500]
 [9300 8800 4600 9000 7800]
 [5900 6500 7700 1200 9400]]


In [89]:
basket_arr = np.array(basket)

In [92]:
basket_arr[::]

array(['apple', 'bananas', 'potato', 'broccoli', 'okra', 'lettuce',
       'cheese', 'yogurt', 'milk'], dtype='<U8')

In [112]:
def func (x):
    return x.upper()

In [122]:
xx = map(lambda x: x.upper()  , basket_arr[::2])
basket_arr[::2]=list(xx)

In [123]:
basket_arr


array(['APPLE', 'bananas', 'POTATO', 'broccoli', 'OKRA', 'lettuce',
       'CHEESE', 'yogurt', 'MILK'], dtype='<U8')

## attributes of arrays --> ndim shape size dtypes

## functions

In [130]:
# nummerical arrays : min , max, mean, std

In [134]:
rand_int = rand_int/100

In [135]:
rand_int

array([[76., 27., 93., 67., 96.],
       [57., 83., 42., 56., 35.],
       [93., 88., 46., 90., 78.],
       [59., 65., 77., 12., 94.]])

In [138]:

print('Maximum  : {}\nMinimum : {} \nMean : {}\nSTD  :{}'.format(rand_int.max(),rand_int.min(), rand_int.mean(), rand_int.std()))

Maximum  : 12.0
Minimum : 96.0 
Mean : 66.7
STD  :23.929270778692775


In [145]:
print('Maximum  : {1:1.0f}\nMinimum : {0:.1f} \nMean : {2:.1f}\nSTD  :{3:.1f}'.format(rand_int.min(),rand_int.max(), rand_int.mean(), rand_int.std()))

Maximum  : 96
Minimum : 12.0 
Mean : 66.7
STD  :23.9


In [148]:
rand_int

array([[76., 27., 93., 67., 96.],
       [57., 83., 42., 56., 35.],
       [93., 88., 46., 90., 78.],
       [59., 65., 77., 12., 94.]])

In [149]:
rand_int.shape

(4, 5)

In [147]:
rand_int.max(axis = 0 )

array([93., 88., 93., 90., 96.])

In [150]:
rand_int.max(axis = 1 )

array([96., 83., 93., 94.])

In [153]:
rand_int3d

array([[[76, 27, 93, 67, 96],
        [57, 83, 42, 56, 35],
        [93, 88, 46, 90, 78],
        [59, 65, 77, 12, 94]],

       [[49, 76, 94, 57, 71],
        [58, 17, 62, 95, 37],
        [44, 86, 50, 13, 79],
        [74, 85, 44, 68, 20]]])

In [154]:
rand_int3d.shape

(2, 4, 5)

In [155]:
rand_int3d.max(axis = 0)

array([[76, 76, 94, 67, 96],
       [58, 83, 62, 95, 37],
       [93, 88, 50, 90, 79],
       [74, 85, 77, 68, 94]])

In [156]:
rand_int3d.max(axis = 1)

array([[93, 88, 93, 90, 96],
       [74, 86, 94, 95, 79]])

In [157]:
rand_int3d.max(axis = 2)

array([[96, 83, 93, 94],
       [94, 95, 86, 85]])

In [159]:
rand_int.mean(axis = 0)

array([71.25, 65.75, 64.5 , 56.25, 75.75])

## for 2 dimensional array / dataframe 
### Axis = 0 | column wise operation
### Axis = 1 | row wise operation

In [164]:
rand_int.shape[0] # row 

4

In [168]:
rand_int[0:4, 3].mean()

56.25

In [162]:
rand_int

array([[76., 27., 93., 67., 96.],
       [57., 83., 42., 56., 35.],
       [93., 88., 46., 90., 78.],
       [59., 65., 77., 12., 94.]])

In [160]:
rand_int.mean(axis = 0)

array([71.25, 65.75, 64.5 , 56.25, 75.75])

In [161]:
rand_int.mean(axis = 1)

array([71.8, 54.6, 79. , 61.4])

In [170]:
rand_int3d.shape

(2, 4, 5)

In [174]:
rand_int3d

array([[[76, 27, 93, 67, 96],
        [57, 83, 42, 56, 35],
        [93, 88, 46, 90, 78],
        [59, 65, 77, 12, 94]],

       [[49, 76, 94, 57, 71],
        [58, 17, 62, 95, 37],
        [44, 86, 50, 13, 79],
        [74, 85, 44, 68, 20]]])

In [171]:
rand_int3d.mean(axis = 0)

array([[62.5, 51.5, 93.5, 62. , 83.5],
       [57.5, 50. , 52. , 75.5, 36. ],
       [68.5, 87. , 48. , 51.5, 78.5],
       [66.5, 75. , 60.5, 40. , 57. ]])

In [175]:
rand_int3d[:, 0,0].mean()

62.5

In [176]:
rand_int3d[ :, 0 ,1].mean()

51.5

In [178]:
rand_int3d.shape

(2, 4, 5)

In [179]:
rand_int.T

array([[76., 57., 93., 59.],
       [27., 83., 88., 65.],
       [93., 42., 46., 77.],
       [67., 56., 90., 12.],
       [96., 35., 78., 94.]])

In [180]:
rand_int.sort()

In [182]:
rand_int.sort(axis = 0 )

In [183]:
rand_int

array([[12., 42., 56., 57., 83.],
       [27., 59., 65., 77., 93.],
       [35., 67., 76., 90., 94.],
       [46., 78., 88., 93., 96.]])

In [184]:
rand_int.sort(axis = 1)

In [185]:
rand_int

array([[12., 42., 56., 57., 83.],
       [27., 59., 65., 77., 93.],
       [35., 67., 76., 90., 94.],
       [46., 78., 88., 93., 96.]])

In [187]:
np.linalg.inv()

TypeError: inv() missing 1 required positional argument: 'a'

In [188]:
import pandas as pd

# Data Wrangling : Extraction / Exxploration /Manipulation of data tables

## Data structures
### 1. Series   : 1 dimensional labelled array hold heterogenous elements 
### 2. Dataframe : 2 dimesnional labelled array hold heterogenous elements

## Creating a series from a dictionary

In [189]:
info = { 'Name' : 'Nimisha', 'Age' : 32, 'Designation' : 'Trainer', 'Salary' : 10000}

In [191]:
np.array(list(info.values()))

array(['Nimisha', '32', 'Trainer', '10000'], dtype='<U7')

In [193]:
ser = pd.Series(info)

In [194]:
ser

Name           Nimisha
Age                 32
Designation    Trainer
Salary           10000
dtype: object

In [196]:
info['Name']

'Nimisha'

In [197]:
ser['Name']

'Nimisha'

In [198]:
ser[0]

'Nimisha'

In [199]:
ser['Age']

32

In [200]:
ser1 = pd.Series(range(1,10))

In [204]:
ser1.sort_values(ascending = False)

8    9
7    8
6    7
5    6
4    5
3    4
2    3
1    2
0    1
dtype: int64

In [213]:
brics = {'country' : ['Brazil','Russia','India','China','South Africa'],
        'capital' : ['Brasilia','Moscow','New Delhi','Beijing',None]}

In [214]:
pd.DataFrame(brics, index = ['B','R','I','C','S'])

country    capital
B        Brazil   Brasilia
R        Russia     Moscow
I         India  New Delhi
C         China    Beijing
S  South Africa       None

# Importing an external data files csv or excel files

### path of working directory  : default path 

In [215]:
# get present working directory

In [216]:
pwd()

'/home/ubuntu/work/Jan 18'

In [217]:
import os 
os.getcwd()

'/home/ubuntu/work/Jan 18'

In [ ]:
pd.read_csv(filepath )

In [ ]:
# bfull address of teh file with filename and extension

In [225]:
pd.read_csv('~/work/data/cars.csv')

Make                              Model    Type  Origin DriveTrain  \
0         Acura                                MDX     SUV    Asia        All   
1         Acura                     RSX Type S 2dr   Sedan    Asia      Front   
2         Acura                            TSX 4dr   Sedan    Asia      Front   
3         Acura                             TL 4dr   Sedan    Asia      Front   
4         Acura                         3.5 RL 4dr   Sedan    Asia      Front   
5         Acura            3.5 RL w/Navigation 4dr   Sedan    Asia      Front   
6         Acura             NSX coupe 2dr manual S  Sports    Asia       Rear   
7          Audi                        A4 1.8T 4dr   Sedan  Europe      Front   
8          Audi             A41.8T convertible 2dr   Sedan  Europe      Front   
9          Audi                         A4 3.0 4dr   Sedan  Europe      Front   
10         Audi          A4 3.0 Quattro 4dr manual   Sedan  Europe        All   
11         Audi            A4 3.0 Quattro 4dr auto   Sedan  Europe        All   
12         Audi                         A6 3.0 4dr   Sedan  Europe      Front   
13         Audi                 A6 3.0 Quattro 4dr   Sedan  Europe        All   
14         Audi             A4 3.0 convertible 2dr   Sedan  Europe      Front   
15         Audi     A4 3.0 Quattro convertible 2dr   Sedan  Europe        All   
16         Audi           A6 2.7 Turbo Quattro 4dr   Sedan  Europe        All   
17         Audi                 A6 4.2 Quattro 4dr   Sedan  Europe        All   
18         Audi                   A8 L Quattro 4dr   Sedan  Europe        All   
19         Audi                     S4 Quattro 4dr   Sedan  Europe        All   
20         Audi                           RS 6 4dr  Sports  Europe      Front   
21         Audi     TT 1.8 convertible 2dr (coupe)  Sports  Europe      Front   
22         Audi   TT 1.8 Quattro 2dr (convertible)  Sports  Europe        All   
23         Audi     TT 3.2 coupe 2dr (convertible)  Sports  Europe        All   
24         Audi               A6 3.0 Avant Quattro   Wagon  Europe        All   
25         Audi                   S4 Avant Quattro   Wagon  Europe        All   
26          BMW                            X3 3.0i     SUV  Europe        All   
27          BMW                            X5 4.4i     SUV  Europe        All   
28          BMW                           325i 4dr   Sedan  Europe       Rear   
29          BMW                          325Ci 2dr   Sedan  Europe       Rear   
..          ...                                ...     ...     ...        ...   
398      Toyota              Tundra Regular Cab V6   Truck    Asia       Rear   
399      Toyota           Tundra Access Cab V6 SR5   Truck    Asia        All   
400      Toyota                          Matrix XR   Wagon    Asia      Front   
401  Volkswagen                         Touareg V6     SUV  Europe        All   
402  Volkswagen                       Golf GLS 4dr   Sedan  Europe      Front   
403  Volkswagen                 GTI 1.8T 2dr hatch   Sedan  Europe      Front   
404  Volkswagen                  Jetta GLS TDI 4dr   Sedan  Europe      Front   
405  Volkswagen            New Beetle GLS 1.8T 2dr   Sedan  Europe      Front   
406  Volkswagen                  Jetta GLI VR6 4dr   Sedan  Europe      Front   
407  Volkswagen     New Beetle GLS convertible 2dr   Sedan  Europe      Front   
408  Volkswagen                     Passat GLS 4dr   Sedan  Europe      Front   
409  Volkswagen          Passat GLX V6 4MOTION 4dr   Sedan  Europe      Front   
410  Volkswagen              Passat W8 4MOTION 4dr   Sedan  Europe      Front   
411  Volkswagen                        Phaeton 4dr   Sedan  Europe      Front   
412  Volkswagen                    Phaeton W12 4dr   Sedan  Europe      Front   
413  Volkswagen                           Jetta GL   Wagon  Europe      Front   
414  Volkswagen                    Passat GLS 1.8T   Wagon  Europe      Front   
415  Volkswagen                          P

In [231]:
os.chdir('/home/ubuntu/work/data/')

In [233]:
car = pd.read_csv('cars.csv')

In [235]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file into DataFrame.
    
    Also supports option

In [ ]:
'~/Downloads/cars.csv'

# basic structure of the data `

In [238]:
print('Shape : ', car.shape)
print('Column names : ', car.columns)
print('Row Labels /Index :',car.index )
print('Datatypes for each column :\n', car.dtypes)

Shape :  (428, 15)
Column names :  Index(['Make', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP', 'Invoice',
       'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway',
       'Weight', 'Wheelbase', 'Length'],
      dtype='object')
Row Labels /Index : RangeIndex(start=0, stop=428, step=1)
Datatypes for each column :
 Make            object
Model           object
Type            object
Origin          object
DriveTrain      object
MSRP           float64
Invoice        float64
EngineSize     float64
Cylinders      float64
Horsepower     float64
MPG_City       float64
MPG_Highway    float64
Weight         float64
Wheelbase      float64
Length         float64
dtype: object


In [239]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 15 columns):
Make           428 non-null object
Model          428 non-null object
Type           428 non-null object
Origin         428 non-null object
DriveTrain     428 non-null object
MSRP           428 non-null float64
Invoice        428 non-null float64
EngineSize     428 non-null float64
Cylinders      426 non-null float64
Horsepower     428 non-null float64
MPG_City       428 non-null float64
MPG_Highway    428 non-null float64
Weight         428 non-null float64
Wheelbase      428 non-null float64
Length         428 non-null float64
dtypes: float64(10), object(5)
memory usage: 50.2+ KB


## Snapshot of the data first 5 rows

In [240]:
car.head() # by default gives first five rows

Make            Model   Type Origin DriveTrain     MSRP  Invoice  \
0  Acura              MDX    SUV   Asia        All  36945.0  33337.0   
1  Acura   RSX Type S 2dr  Sedan   Asia      Front  23820.0  21761.0   
2  Acura          TSX 4dr  Sedan   Asia      Front  26990.0  24647.0   
3  Acura           TL 4dr  Sedan   Asia      Front  33195.0  30299.0   
4  Acura       3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      17.0         23.0  4451.0   
1         2.0        4.0       200.0      24.0         31.0  2778.0   
2         2.4        4.0       200.0      22.0         29.0  3230.0   
3         3.2        6.0       270.0      20.0         28.0  3575.0   
4         3.5        6.0       225.0      18.0         24.0  3880.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0

In [241]:
car.tail() # last 5 rows

Make                     Model   Type  Origin DriveTrain     MSRP  \
423  Volvo   C70 LPT convertible 2dr  Sedan  Europe      Front  40565.0   
424  Volvo   C70 HPT convertible 2dr  Sedan  Europe      Front  42565.0   
425  Volvo                S80 T6 4dr  Sedan  Europe      Front  45210.0   
426  Volvo                       V40  Wagon  Europe      Front  26135.0   
427  Volvo                      XC70  Wagon  Europe        All  35145.0   

     Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  \
423  38203.0         2.4        5.0       197.0      21.0         28.0   
424  40083.0         2.3        5.0       242.0      20.0         26.0   
425  42573.0         2.9        6.0       268.0      19.0         26.0   
426  24641.0         1.9        4.0       170.0      22.0         29.0   
427  33112.0         2.5        5.0       208.0      20.0         27.0   

     Weight  Wheelbase  Length  
423  3450.0      105.0   186.0  
424  3450.0      105.0   186.0  
425  3653.0      110.0   190.0  
426  2822.0      101.0   180.0  
427  3823.0      109.0   186.0

In [242]:
car.head(2)

Make            Model   Type Origin DriveTrain     MSRP  Invoice  \
0  Acura              MDX    SUV   Asia        All  36945.0  33337.0   
1  Acura   RSX Type S 2dr  Sedan   Asia      Front  23820.0  21761.0   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
0         3.5        6.0       265.0      17.0         23.0  4451.0   
1         2.0        4.0       200.0      24.0         31.0  2778.0   

   Wheelbase  Length  
0      106.0   189.0  
1      101.0   172.0

In [243]:
car.tail(2)

Make  Model   Type  Origin DriveTrain     MSRP  Invoice  EngineSize  \
426  Volvo    V40  Wagon  Europe      Front  26135.0  24641.0         1.9   
427  Volvo   XC70  Wagon  Europe        All  35145.0  33112.0         2.5   

     Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length  
426        4.0       170.0      22.0         29.0  2822.0      101.0   180.0  
427        5.0       208.0      20.0         27.0  3823.0      109.0   186.0

# access the rows and columns

## Access columns

In [245]:
car.Make # column as a Series 

0           Acura
1           Acura
2           Acura
3           Acura
4           Acura
5           Acura
6           Acura
7            Audi
8            Audi
9            Audi
10           Audi
11           Audi
12           Audi
13           Audi
14           Audi
15           Audi
16           Audi
17           Audi
18           Audi
19           Audi
20           Audi
21           Audi
22           Audi
23           Audi
24           Audi
25           Audi
26            BMW
27            BMW
28            BMW
29            BMW
          ...    
398        Toyota
399        Toyota
400        Toyota
401    Volkswagen
402    Volkswagen
403    Volkswagen
404    Volkswagen
405    Volkswagen
406    Volkswagen
407    Volkswagen
408    Volkswagen
409    Volkswagen
410    Volkswagen
411    Volkswagen
412    Volkswagen
413    Volkswagen
414    Volkswagen
415    Volkswagen
416         Volvo
417         Volvo
418         Volvo
419         Volvo
420         Volvo
421         Volvo
422       

In [246]:
car['Make'] # column as a Series

0           Acura
1           Acura
2           Acura
3           Acura
4           Acura
5           Acura
6           Acura
7            Audi
8            Audi
9            Audi
10           Audi
11           Audi
12           Audi
13           Audi
14           Audi
15           Audi
16           Audi
17           Audi
18           Audi
19           Audi
20           Audi
21           Audi
22           Audi
23           Audi
24           Audi
25           Audi
26            BMW
27            BMW
28            BMW
29            BMW
          ...    
398        Toyota
399        Toyota
400        Toyota
401    Volkswagen
402    Volkswagen
403    Volkswagen
404    Volkswagen
405    Volkswagen
406    Volkswagen
407    Volkswagen
408    Volkswagen
409    Volkswagen
410    Volkswagen
411    Volkswagen
412    Volkswagen
413    Volkswagen
414    Volkswagen
415    Volkswagen
416         Volvo
417         Volvo
418         Volvo
419         Volvo
420         Volvo
421         Volvo
422       

### access multiple columns

In [249]:
car[['Make','Model']] # as a dataframe

Make                              Model
0         Acura                                MDX
1         Acura                     RSX Type S 2dr
2         Acura                            TSX 4dr
3         Acura                             TL 4dr
4         Acura                         3.5 RL 4dr
5         Acura            3.5 RL w/Navigation 4dr
6         Acura             NSX coupe 2dr manual S
7          Audi                        A4 1.8T 4dr
8          Audi             A41.8T convertible 2dr
9          Audi                         A4 3.0 4dr
10         Audi          A4 3.0 Quattro 4dr manual
11         Audi            A4 3.0 Quattro 4dr auto
12         Audi                         A6 3.0 4dr
13         Audi                 A6 3.0 Quattro 4dr
14         Audi             A4 3.0 convertible 2dr
15         Audi     A4 3.0 Quattro convertible 2dr
16         Audi           A6 2.7 Turbo Quattro 4dr
17         Audi                 A6 4.2 Quattro 4dr
18         Audi                   A8 L Quattro 4dr
19         Audi                     S4 Quattro 4dr
20         Audi                           RS 6 4dr
21         Audi     TT 1.8 convertible 2dr (coupe)
22         Audi   TT 1.8 Quattro 2dr (convertible)
23         Audi     TT 3.2 coupe 2dr (convertible)
24         Audi               A6 3.0 Avant Quattro
25         Audi                   S4 Avant Quattro
26          BMW                            X3 3.0i
27          BMW                            X5 4.4i
28          BMW                           325i 4dr
29          BMW                          325Ci 2dr
..          ...                                ...
398      Toyota              Tundra Regular Cab V6
399      Toyota           Tundra Access Cab V6 SR5
400      Toyota                          Matrix XR
401  Volkswagen                         Touareg V6
402  Volkswagen                       Golf GLS 4dr
403  Volkswagen                 GTI 1.8T 2dr hatch
404  Volkswagen                  Jetta GLS TDI 4dr
405  Volkswagen            New Beetle GLS 1.8T 2dr
406  Volkswagen                  Jetta GLI VR6 4dr
407  Volkswagen     New Beetle GLS convertible 2dr
408  Volkswagen                     Passat GLS 4dr
409  Volkswagen          Passat GLX V6 4MOTION 4dr
410  Volkswagen              Passat W8 4MOTION 4dr
411  Volkswagen                        Phaeton 4dr
412  Volkswagen                    Phaeton W12 4dr
413  Volkswagen                           Jetta GL
414  Volkswagen                    Passat GLS 1.8T
415  Volkswagen                          Passat W8
416       Volvo                            XC90 T6
417       Volvo                            S40 4dr
418       Volvo                        S60 2.5 4dr
419       Volvo                         S60 T5 4dr
420       Volvo                          S60 R 4dr
421       Volvo                        S80 2.9 4dr
422       Volvo                       S80 2.5T 4dr
423       Volvo            C70 LPT convertible 2dr
424       Volvo            C70 HPT convertible 2dr
425       Volvo                         S80 T6 4dr
426       Volvo                                V40
427       Volvo                               XC70

[428 rows x 2 columns]

In [250]:
car[['Make']] # return 1 colummn as a dataframe

Make
0         Acura
1         Acura
2         Acura
3         Acura
4         Acura
5         Acura
6         Acura
7          Audi
8          Audi
9          Audi
10         Audi
11         Audi
12         Audi
13         Audi
14         Audi
15         Audi
16         Audi
17         Audi
18         Audi
19         Audi
20         Audi
21         Audi
22         Audi
23         Audi
24         Audi
25         Audi
26          BMW
27          BMW
28          BMW
29          BMW
..          ...
398      Toyota
399      Toyota
400      Toyota
401  Volkswagen
402  Volkswagen
403  Volkswagen
404  Volkswagen
405  Volkswagen
406  Volkswagen
407  Volkswagen
408  Volkswagen
409  Volkswagen
410  Volkswagen
411  Volkswagen
412  Volkswagen
413  Volkswagen
414  Volkswagen
415  Volkswagen
416       Volvo
417       Volvo
418       Volvo
419       Volvo
420       Volvo
421       Volvo
422       Volvo
423       Volvo
424       Volvo
425       Volvo
426       Volvo
427       Volvo

[428 rows x 1 columns]

# acccesing rows

## acccesing slice of rows

In [253]:
car[2:50:4]

Make                              Model    Type  Origin DriveTrain  \
2   Acura                            TSX 4dr   Sedan    Asia      Front   
6   Acura             NSX coupe 2dr manual S  Sports    Asia       Rear   
10   Audi          A4 3.0 Quattro 4dr manual   Sedan  Europe        All   
14   Audi             A4 3.0 convertible 2dr   Sedan  Europe      Front   
18   Audi                   A8 L Quattro 4dr   Sedan  Europe        All   
22   Audi   TT 1.8 Quattro 2dr (convertible)  Sports  Europe        All   
26    BMW                            X3 3.0i     SUV  Europe        All   
30    BMW              325Ci convertible 2dr   Sedan  Europe       Rear   
34    BMW                          330xi 4dr   Sedan  Europe        All   
38    BMW                          545iA 4dr   Sedan  Europe       Rear   
42    BMW                 M3 convertible 2dr  Sports  Europe       Rear   
46  Buick                            Rainier     SUV     USA        All   

       MSRP  Invoice  EngineSize  Cylinders  Horsepower  MPG_City  \
2   26990.0  24647.0         2.4        4.0       200.0      22.0   
6   89765.0  79978.0         3.2        6.0       290.0      17.0   
10  33430.0  30366.0         3.0        6.0       220.0      17.0   
14  42490.0  38325.0         3.0        6.0       220.0      20.0   
18  69190.0  64740.0         4.2        8.0       330.0      17.0   
22  37390.0  33891.0         1.8        4.0       225.0      20.0   
26  37000.0  33873.0         3.0        6.0       225.0      16.0   
30  37995.0  34800.0         2.5        6.0       184.0      19.0   
34  37245.0  34115.0         3.0        6.0       225.0      20.0   
38  54995.0  50270.0         4.4        8.0       325.0      18.0   
42  56595.0  51815.0         3.2        6.0       333.0      16.0   
46  37895.0  34357.0         4.2        6.0       275.0      15.0   

    MPG_Highway  Weight  Wheelbase  Length  
2          29.0  3230.0      105.0   183.0  
6          24.0  3153.0      100.0   174.0  
10         26.0  3583.0      104.0   179.0  
14         27.0  3814.0      105.0   180.0  
18         24.0  4399.0      121.0   204.0  
22         28.0  2921.0       96.0   159.0  
26         23.0  4023.0      110.0   180.0  
30         27.0  3560.0      107.0   177.0  
34         29.0  3483.0      107.0   176.0  
38         26.0  3814.0      114.0   191.0  
42         23.0  3781.0      108.0   177.0  
46         21.0  4600.0      113.0   193.0

# for accessing single rows and random rows annd rows and colummns together

## df.loc[ ]

In [257]:
car.loc[2] # as a Series label = 2

Make              Acura
Model           TSX 4dr
Type              Sedan
Origin             Asia
DriveTrain        Front
MSRP              26990
Invoice           24647
EngineSize          2.4
Cylinders             4
Horsepower          200
MPG_City             22
MPG_Highway          29
Weight             3230
Wheelbase           105
Length              183
Name: 2, dtype: object

In [259]:
car.loc[[2,4,6,7,1]] # as dataframe label = 2

Make                    Model    Type  Origin DriveTrain     MSRP  \
2  Acura                  TSX 4dr   Sedan    Asia      Front  26990.0   
4  Acura               3.5 RL 4dr   Sedan    Asia      Front  43755.0   
6  Acura   NSX coupe 2dr manual S  Sports    Asia       Rear  89765.0   
7   Audi              A4 1.8T 4dr   Sedan  Europe      Front  25940.0   
1  Acura           RSX Type S 2dr   Sedan    Asia      Front  23820.0   

   Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
2  24647.0         2.4        4.0       200.0      22.0         29.0  3230.0   
4  39014.0         3.5        6.0       225.0      18.0         24.0  3880.0   
6  79978.0         3.2        6.0       290.0      17.0         24.0  3153.0   
7  23508.0         1.8        4.0       170.0      22.0         31.0  3252.0   
1  21761.0         2.0        4.0       200.0      24.0         31.0  2778.0   

   Wheelbase  Length  
2      105.0   183.0  
4      115.0   197.0  
6      100.0   174.0  
7      104.0   179.0  
1      101.0   172.0

In [260]:
car.loc[[2,3,4,5,6], ['Make','Model']]

Make                     Model
2  Acura                   TSX 4dr
3  Acura                    TL 4dr
4  Acura                3.5 RL 4dr
5  Acura   3.5 RL w/Navigation 4dr
6  Acura    NSX coupe 2dr manual S

In [261]:
car.loc[2, 'Make']

'Acura'

In [262]:
car.loc[2, ['Make','DriveTrain']]

Make          Acura
DriveTrain    Front
Name: 2, dtype: object

In [263]:
car.loc[[2,100], 'Make']

2         Acura
100    Chrysler
Name: Make, dtype: object

In [267]:
car.loc[2:5 , 'Make':'Cylinders']

Make                     Model   Type Origin DriveTrain     MSRP  Invoice  \
2  Acura                   TSX 4dr  Sedan   Asia      Front  26990.0  24647.0   
3  Acura                    TL 4dr  Sedan   Asia      Front  33195.0  30299.0   
4  Acura                3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0   
5  Acura   3.5 RL w/Navigation 4dr  Sedan   Asia      Front  46100.0  41100.0   

   EngineSize  Cylinders  
2         2.4        4.0  
3         3.2        6.0  
4         3.5        6.0  
5         3.5        6.0

In [269]:
car.loc[2:5] # label

Make                     Model   Type Origin DriveTrain     MSRP  Invoice  \
2  Acura                   TSX 4dr  Sedan   Asia      Front  26990.0  24647.0   
3  Acura                    TL 4dr  Sedan   Asia      Front  33195.0  30299.0   
4  Acura                3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0   
5  Acura   3.5 RL w/Navigation 4dr  Sedan   Asia      Front  46100.0  41100.0   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
2         2.4        4.0       200.0      22.0         29.0  3230.0   
3         3.2        6.0       270.0      20.0         28.0  3575.0   
4         3.5        6.0       225.0      18.0         24.0  3880.0   
5         3.5        6.0       225.0      18.0         24.0  3893.0   

   Wheelbase  Length  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0  
5      115.0   197.0

In [268]:
car[2:5] # index

Make        Model   Type Origin DriveTrain     MSRP  Invoice  EngineSize  \
2  Acura      TSX 4dr  Sedan   Asia      Front  26990.0  24647.0         2.4   
3  Acura       TL 4dr  Sedan   Asia      Front  33195.0  30299.0         3.2   
4  Acura   3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0         3.5   

   Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length  
2        4.0       200.0      22.0         29.0  3230.0      105.0   183.0  
3        6.0       270.0      20.0         28.0  3575.0      108.0   186.0  
4        6.0       225.0      18.0         24.0  3880.0      115.0   197.0

In [ ]:
car.iloc

In [278]:
car.index

RangeIndex(start=0, stop=428, step=1)

In [274]:
br = pd.DataFrame(brics, index = ['A','B','C','D','E'])
br

country    capital
A        Brazil   Brasilia
B        Russia     Moscow
C         India  New Delhi
D         China    Beijing
E  South Africa       None

In [276]:
br.loc['A':'B']

country   capital
A  Brazil  Brasilia
B  Russia    Moscow

In [277]:
br[0:1]

country   capital
A  Brazil  Brasilia

# df.iloc[ ] 

In [279]:
car.iloc[2:5] # index

Make        Model   Type Origin DriveTrain     MSRP  Invoice  EngineSize  \
2  Acura      TSX 4dr  Sedan   Asia      Front  26990.0  24647.0         2.4   
3  Acura       TL 4dr  Sedan   Asia      Front  33195.0  30299.0         3.2   
4  Acura   3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0         3.5   

   Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length  
2        4.0       200.0      22.0         29.0  3230.0      105.0   183.0  
3        6.0       270.0      20.0         28.0  3575.0      108.0   186.0  
4        6.0       225.0      18.0         24.0  3880.0      115.0   197.0

In [280]:
car.iloc[[2,3,4,5]]

Make                     Model   Type Origin DriveTrain     MSRP  Invoice  \
2  Acura                   TSX 4dr  Sedan   Asia      Front  26990.0  24647.0   
3  Acura                    TL 4dr  Sedan   Asia      Front  33195.0  30299.0   
4  Acura                3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0   
5  Acura   3.5 RL w/Navigation 4dr  Sedan   Asia      Front  46100.0  41100.0   

   EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
2         2.4        4.0       200.0      22.0         29.0  3230.0   
3         3.2        6.0       270.0      20.0         28.0  3575.0   
4         3.5        6.0       225.0      18.0         24.0  3880.0   
5         3.5        6.0       225.0      18.0         24.0  3893.0   

   Wheelbase  Length  
2      105.0   183.0  
3      108.0   186.0  
4      115.0   197.0  
5      115.0   197.0

In [282]:
car.iloc[2,0] # row = 2 ccolumn = Make

'Acura'

In [284]:
car.iloc[ 3 , 0:5]

Make            Acura
Model          TL 4dr
Type            Sedan
Origin           Asia
DriveTrain      Front
Name: 3, dtype: object

# Filter the data for desired information

In [285]:
car.Make == 'BMW' # Series with corresponding to each row True or False

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26      True
27      True
28      True
29      True
       ...  
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
Name: Make, Length: 428, dtype: bool

In [287]:
car[car.Make == 'BMW']

Make                     Model    Type  Origin DriveTrain     MSRP  \
26  BMW                   X3 3.0i     SUV  Europe        All  37000.0   
27  BMW                   X5 4.4i     SUV  Europe        All  52195.0   
28  BMW                  325i 4dr   Sedan  Europe       Rear  28495.0   
29  BMW                 325Ci 2dr   Sedan  Europe       Rear  30795.0   
30  BMW     325Ci convertible 2dr   Sedan  Europe       Rear  37995.0   
31  BMW                 325xi 4dr   Sedan  Europe        All  30245.0   
32  BMW                  330i 4dr   Sedan  Europe       Rear  35495.0   
33  BMW                 330Ci 2dr   Sedan  Europe       Rear  36995.0   
34  BMW                 330xi 4dr   Sedan  Europe        All  37245.0   
35  BMW                  525i 4dr   Sedan  Europe       Rear  39995.0   
36  BMW     330Ci convertible 2dr   Sedan  Europe       Rear  44295.0   
37  BMW                  530i 4dr   Sedan  Europe       Rear  44995.0   
38  BMW                 545iA 4dr   Sedan  Europe       Rear  54995.0   
39  BMW                  745i 4dr   Sedan  Europe       Rear  69195.0   
40  BMW                 745Li 4dr   Sedan  Europe       Rear  73195.0   
41  BMW              M3 coupe 2dr  Sports  Europe       Rear  48195.0   
42  BMW        M3 convertible 2dr  Sports  Europe       Rear  56595.0   
43  BMW   Z4 convertible 2.5i 2dr  Sports  Europe       Rear  33895.0   
44  BMW   Z4 convertible 3.0i 2dr  Sports  Europe       Rear  41045.0   
45  BMW               325xi Sport   Wagon  Europe        All  32845.0   

    Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
26  33873.0         3.0        6.0       225.0      16.0         23.0  4023.0   
27  47720.0         4.4        8.0       325.0      16.0         22.0  4824.0   
28  26155.0         2.5        6.0       184.0      20.0         29.0  3219.0   
29  28245.0         2.5        6.0       184.0      20.0         29.0  3197.0   
30  34800.0         2.5        6.0       184.0      19.0         27.0  3560.0   
31  27745.0         2.5        6.0       184.0      19.0         27.0  3461.0   
32  32525.0         3.0        6.0       225.0      20.0         30.0  3285.0   
33  33890.0         3.0        6.0       225.0      20.0         30.0  3285.0   
34  34115.0         3.0        6.0       225.0      20.0         29.0  3483.0   
35  36620.0         2.5        6.0       184.0      19.0         28.0  3428.0   
36  40530.0         3.0        6.0       225.0      19.0         28.0  3616.0   
37  41170.0         3.0        6.0       225.0      20.0         30.0  3472.0   
38  50270.0         4.4        8.0       325.0      18.0         26.0  3814.0   
39  63190.0         4.4        8.0       325.0      18.0         26.0  4376.0   
40  66830.0         4.4        8.0       325.0      18.0         26.0  4464.0   
41  44170.0         3.2        6.0       333.0      16.0         24.0  3415.0   
42  51815.0         3.2        6.0       333.0      16.0         23.0  3781.0   
43  31065.0         2.5        6.0       184.0      20.0         28.0  2932.0   
44  37575.0         3.0        6.0       225.0      21.0         29.0  2998.0   
45  30110.0         2.5        6.0       184.0      19.0         26.0  3594.0   

    Wheelbase  Length  
26      110.0   180.0  
27      111.0   184.0  
28      107.0   176.0  
29      107.0   177.0  
30      107.0   177.0  
31      107.0   176.0  
32      107.0   176.0  
33      107.0   176.0  
34      107.0   176.0  
35      114.0   191.0  
36      107.0   177.0  
37      114.0   191.0  
38      114.0   191.0  
39      118.0   198.0  
40      123.0   204.0  
41      108.0   177.0  
42      108.0   177.0  
43       98.0   161.0  
44       98.0   161.0  
45      107.0   176.0

In [288]:
car.loc[car.Make == 'BMW', 'Make' : 'Cylinders']

Make                     Model    Type  Origin DriveTrain     MSRP  \
26  BMW                   X3 3.0i     SUV  Europe        All  37000.0   
27  BMW                   X5 4.4i     SUV  Europe        All  52195.0   
28  BMW                  325i 4dr   Sedan  Europe       Rear  28495.0   
29  BMW                 325Ci 2dr   Sedan  Europe       Rear  30795.0   
30  BMW     325Ci convertible 2dr   Sedan  Europe       Rear  37995.0   
31  BMW                 325xi 4dr   Sedan  Europe        All  30245.0   
32  BMW                  330i 4dr   Sedan  Europe       Rear  35495.0   
33  BMW                 330Ci 2dr   Sedan  Europe       Rear  36995.0   
34  BMW                 330xi 4dr   Sedan  Europe        All  37245.0   
35  BMW                  525i 4dr   Sedan  Europe       Rear  39995.0   
36  BMW     330Ci convertible 2dr   Sedan  Europe       Rear  44295.0   
37  BMW                  530i 4dr   Sedan  Europe       Rear  44995.0   
38  BMW                 545iA 4dr   Sedan  Europe       Rear  54995.0   
39  BMW                  745i 4dr   Sedan  Europe       Rear  69195.0   
40  BMW                 745Li 4dr   Sedan  Europe       Rear  73195.0   
41  BMW              M3 coupe 2dr  Sports  Europe       Rear  48195.0   
42  BMW        M3 convertible 2dr  Sports  Europe       Rear  56595.0   
43  BMW   Z4 convertible 2.5i 2dr  Sports  Europe       Rear  33895.0   
44  BMW   Z4 convertible 3.0i 2dr  Sports  Europe       Rear  41045.0   
45  BMW               325xi Sport   Wagon  Europe        All  32845.0   

    Invoice  EngineSize  Cylinders  
26  33873.0         3.0        6.0  
27  47720.0         4.4        8.0  
28  26155.0         2.5        6.0  
29  28245.0         2.5        6.0  
30  34800.0         2.5        6.0  
31  27745.0         2.5        6.0  
32  32525.0         3.0        6.0  
33  33890.0         3.0        6.0  
34  34115.0         3.0        6.0  
35  36620.0         2.5        6.0  
36  40530.0         3.0        6.0  
37  41170.0         3.0        6.0  
38  50270.0         4.4        8.0  
39  63190.0         4.4        8.0  
40  66830.0         4.4        8.0  
41  44170.0         3.2        6.0  
42  51815.0         3.2        6.0  
43  31065.0         2.5        6.0  
44  37575.0         3.0        6.0  
45  30110.0         2.5        6.0

In [289]:
car.loc[car.MSRP >= 45000 , 'Make' : 'Cylinders']

Make                                 Model    Type  Origin  \
5            Acura               3.5 RL w/Navigation 4dr   Sedan    Asia   
6            Acura                NSX coupe 2dr manual S  Sports    Asia   
17            Audi                    A6 4.2 Quattro 4dr   Sedan  Europe   
18            Audi                      A8 L Quattro 4dr   Sedan  Europe   
19            Audi                        S4 Quattro 4dr   Sedan  Europe   
20            Audi                              RS 6 4dr  Sports  Europe   
25            Audi                      S4 Avant Quattro   Wagon  Europe   
27             BMW                               X5 4.4i     SUV  Europe   
38             BMW                             545iA 4dr   Sedan  Europe   
39             BMW                              745i 4dr   Sedan  Europe   
40             BMW                             745Li 4dr   Sedan  Europe   
41             BMW                          M3 coupe 2dr  Sports  Europe   
42             BMW                    M3 convertible 2dr  Sports  Europe   
55        Cadillac                              Escalade     SUV     USA   
56        Cadillac                                SRX V8     SUV     USA   
58        Cadillac                           Deville 4dr   Sedan     USA   
59        Cadillac                       Deville DTS 4dr   Sedan     USA   
60        Cadillac                       Seville SLS 4dr   Sedan     USA   
61        Cadillac                   XLR convertible 2dr  Sports     USA   
62        Cadillac                          Escalade EXT   Truck     USA   
83       Chevrolet              Corvette convertible 2dr  Sports     USA   
114          Dodge          Viper SRT-10 convertible 2dr  Sports     USA   
143            GMC                     Yukon XL 2500 SLT     SUV     USA   
166         Hummer                                    H2     SUV     USA   
184       Infiniti                        Q45 Luxury 4dr   Sedan    Asia   
192         Jaguar                        S-Type 4.2 4dr   Sedan  Europe   
193         Jaguar                          S-Type R 4dr   Sedan  Europe   
194         Jaguar                       Vanden Plas 4dr   Sedan  Europe   
195         Jaguar                               XJ8 4dr   Sedan  Europe   
196         Jaguar                               XJR 4dr   Sedan  Europe   
..             ...                                   ...     ...     ...   
227          Lexus                SC 430 convertible 2dr  Sports    Asia   
229        Lincoln                      Navigator Luxury     SUV     USA   
237        Lincoln               Town Car Ultimate L 4dr   Sedan     USA   
251  Mercedes-Benz                                  G500     SUV  Europe   
252  Mercedes-Benz                                 ML500     SUV  Europe   
260  Mercedes-Benz                           C32 AMG 4dr   Sedan  Europe   
261  Mercedes-Benz                             CL500 2dr   Sedan  Europe   
262  Mercedes-Benz                             CL600 2dr   Sedan  Europe   
263  Mercedes-Benz        CLK320 coupe 2dr (convertible)   Sedan  Europe   
264  Mercedes-Benz        CLK500 coupe 2dr (convertible)   Sedan  Europe   
265  Mercedes-Benz                              E320 4dr   Sedan  Europe   
266  Mercedes-Benz                              E500 4dr   Sedan  Europe   
267  Mercedes-Benz                              S430 4dr   Sedan  Europe   
268  Mercedes-Benz                              S500 4dr   Sedan  Europe   
269  Mercedes-Benz                 SL500 convertible 2dr  Sports  Europe   
270  Mercedes-Benz                          SL55 AMG 2dr  Sports  Europe   
271  Mercedes-Benz                 SL600 convertible 2dr  Sports  Europe   
273  Mercedes-Benz                         SLK32 AMG 2dr  Sports  Europe   
275  Mercedes-Benz                                  E320   Wagon  Europe   
276  Mercedes-Benz                                  E500   Wagon  Europe   
330        Porsche                             Cayenne S     S

## get the data MSRP > 45000 for BMW cars 

In [291]:
car.loc[(car.MSRP >= 45000) & (car.Make == 'BMW') , 'Make' : 'Cylinders']

Make                Model    Type  Origin DriveTrain     MSRP  Invoice  \
27  BMW              X5 4.4i     SUV  Europe        All  52195.0  47720.0   
38  BMW            545iA 4dr   Sedan  Europe       Rear  54995.0  50270.0   
39  BMW             745i 4dr   Sedan  Europe       Rear  69195.0  63190.0   
40  BMW            745Li 4dr   Sedan  Europe       Rear  73195.0  66830.0   
41  BMW         M3 coupe 2dr  Sports  Europe       Rear  48195.0  44170.0   
42  BMW   M3 convertible 2dr  Sports  Europe       Rear  56595.0  51815.0   

    EngineSize  Cylinders  
27         4.4        8.0  
38         4.4        8.0  
39         4.4        8.0  
40         4.4        8.0  
41         3.2        6.0  
42         3.2        6.0

## get the data for Audi and BMW and Honda

In [298]:
car[(car.Make.isin(['Audi','BMW',"Honda"])) & (car.MSRP >= 45000) ]

Make                Model    Type  Origin DriveTrain     MSRP  Invoice  \
17  Audi   A6 4.2 Quattro 4dr   Sedan  Europe        All  49690.0  44936.0   
18  Audi     A8 L Quattro 4dr   Sedan  Europe        All  69190.0  64740.0   
19  Audi       S4 Quattro 4dr   Sedan  Europe        All  48040.0  43556.0   
20  Audi             RS 6 4dr  Sports  Europe      Front  84600.0  76417.0   
25  Audi     S4 Avant Quattro   Wagon  Europe        All  49090.0  44446.0   
27   BMW              X5 4.4i     SUV  Europe        All  52195.0  47720.0   
38   BMW            545iA 4dr   Sedan  Europe       Rear  54995.0  50270.0   
39   BMW             745i 4dr   Sedan  Europe       Rear  69195.0  63190.0   
40   BMW            745Li 4dr   Sedan  Europe       Rear  73195.0  66830.0   
41   BMW         M3 coupe 2dr  Sports  Europe       Rear  48195.0  44170.0   
42   BMW   M3 convertible 2dr  Sports  Europe       Rear  56595.0  51815.0   

    EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
17         4.2        8.0       300.0      17.0         24.0  4024.0   
18         4.2        8.0       330.0      17.0         24.0  4399.0   
19         4.2        8.0       340.0      14.0         20.0  3825.0   
20         4.2        8.0       450.0      15.0         22.0  4024.0   
25         4.2        8.0       340.0      15.0         21.0  3936.0   
27         4.4        8.0       325.0      16.0         22.0  4824.0   
38         4.4        8.0       325.0      18.0         26.0  3814.0   
39         4.4        8.0       325.0      18.0         26.0  4376.0   
40         4.4        8.0       325.0      18.0         26.0  4464.0   
41         3.2        6.0       333.0      16.0         24.0  3415.0   
42         3.2        6.0       333.0      16.0         23.0  3781.0   

    Wheelbase  Length  
17      109.0   193.0  
18      121.0   204.0  
19      104.0   179.0  
20      109.0   191.0  
25      104.0   179.0  
27      111.0   184.0  
38      114.0   191.0  
39      118.0   198.0  
40      123.0   204.0  
41      108.0   177.0  
42      108.0   177.0

## how to get unique items of a column 

In [299]:
car.Make.unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'MINI', 'Mazda', 'Mercedes-Benz', 'Mercury',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

## how many unique items are there in a column

In [300]:
car.Make.nunique()

38

## Are there any duplicates rows ??? # exact duplicates
#### returns a series corresponding each row True or False | True if the row is duplicate of any previous row 

In [303]:
car.duplicated() 

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
Length: 428, dtype: bool

## Any row duplicated only for a particular column

In [304]:
car.duplicated('Make')

0      False
1       True
2       True
3       True
4       True
5       True
6       True
7      False
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26     False
27      True
28      True
29      True
       ...  
398     True
399     True
400     True
401    False
402     True
403     True
404     True
405     True
406     True
407     True
408     True
409     True
410     True
411     True
412     True
413     True
414     True
415     True
416    False
417     True
418     True
419     True
420     True
421     True
422     True
423     True
424     True
425     True
426     True
427     True
Length: 428, dtype: bool

## Any row duplicated only for a combination of columns

In [308]:
car.duplicated(['Make','Model']).any() # returns true if there is even a single true value

True

In [309]:
car[car.duplicated(['Make','Model'])]

Make      Model   Type  Origin DriveTrain     MSRP  Invoice  \
181       Infiniti    G35 4dr  Sedan    Asia        All  32445.0  29783.0   
256  Mercedes-Benz   C240 4dr  Sedan  Europe        All  33480.0  31187.0   
259  Mercedes-Benz   C320 4dr  Sedan  Europe        All  38830.0  36162.0   

     EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
181         3.5        6.0       260.0      18.0         26.0  3677.0   
256         2.6        6.0       168.0      19.0         25.0  3360.0   
259         3.2        6.0       215.0      19.0         27.0  3450.0   

     Wheelbase  Length  
181      112.0   187.0  
256      107.0   178.0  
259      107.0   178.0

### filter data for Make = Mercedes-Benz Model = C320 4dr

In [315]:
car[(car.Make == 'Mercedes-Benz') & (car.Model == ' C320 4dr')]

Make      Model   Type  Origin DriveTrain     MSRP  Invoice  \
258  Mercedes-Benz   C320 4dr  Sedan  Europe       Rear  37630.0  35046.0   
259  Mercedes-Benz   C320 4dr  Sedan  Europe        All  38830.0  36162.0   

     EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  \
258         3.2        6.0       215.0      20.0         26.0  3450.0   
259         3.2        6.0       215.0      19.0         27.0  3450.0   

     Wheelbase  Length  
258      107.0   178.0  
259      107.0   178.0