# Loops : iterations 

## 1. for loop : iterate over a sequence ( string list tuple...)

In [5]:
print('N')
print('i')
print('m')
print('i')

N
i
m
i


In [6]:
for i in 'Python' :
    print(i)

P
y
t
h
o
n


In [3]:
basket = ['apple','bananas', 'potato', 'broccoli', 'okra','lettuce', 'cheese', 'yogurt', 'milk']

In [7]:
for i in basket :
    print(i)

apple
bananas
potato
broccoli
okra
lettuce
cheese
yogurt
milk


# print all the other elements and in all caps 

In [8]:
basket[ : : 2]

['apple', 'potato', 'okra', 'cheese', 'milk']

In [9]:
for i in [0,2,4,6,8]:
    print(basket[i].upper())

APPLE
POTATO
OKRA
CHEESE
MILK


## print my name 10 times 

In [10]:
for i in [0,1,2,3,4,5,6,7,8,9]:
    print('Nimisha')

Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha


#  range() --> generates a sequence of int values 
## range(stop) --> this will create a range objecct starting from 0 till stop value (excluding stop)
## range(start, stop [, step ]) --> this will create a range object starting from start (included) till stop(excluding)

In [11]:
range(10) # iteration object 

range(0, 10)

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
for i in range(10):
    print('Nimisha')

Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha
Nimisha


In [15]:
for i in range(0 , len(basket), 2):
    print(basket[i].upper())

APPLE
POTATO
OKRA
CHEESE
MILK


In [20]:
range(1,6)

range(1, 6)

## 2. while loop : executes till the time an exxpression is true 

In [25]:
num = 0
while num < 10 :
    print(num, end = '\n')
    num += 1

0
1
2
3
4
5
6
7
8
9


## Compute factorial of any number
### 5! = 5 * 4 * 3 * 2 * 1

In [27]:
num = int(input('Please enter a number :'))
fac = 1
for i in range(num , 0, -1):
    print(fac, '*', i , '=', fac *i)     
    fac *= i
    

Please enter a number : 5


1 * 5 = 5
5 * 4 = 20
20 * 3 = 60
60 * 2 = 120
120 * 1 = 120


In [33]:
num = int(input('Please enter a number :'))
fac2 = 1
while num >=1:
    print(fac2, '*', num , '=', fac2 *num)     
    fac2 *= num
    num -= 1


Please enter a number : 5


1 * 5 = 5
5 * 4 = 20
20 * 3 = 60
60 * 2 = 120
120 * 1 = 120


In [30]:
# a += 1 ==> a = a+1

## check if a number is prime or not 
#### num which is only divisible by 1 and itself 
#### need to check the divisibilty of the number from 2 to num -1

In [37]:
num = int(input('Please enter a number :'))
result = 'Prime'
for i in range(2, num ):
    if num % i == 0 :
        result = 'Non Prime'
print(result)

Please enter a number : 12


Non Prime


In [38]:
i

11

# flow control statements :
## break : terminate the loop 
## continue : skip the remaining steps in the iteration

In [39]:
num = int(input('Please enter a number :'))
result = 'Prime'
for i in range(2, num ):
    if num % i == 0 :
        result = 'Non Prime'
        break
print(result)

Please enter a number : 32


Non Prime


In [40]:
i

2

In [43]:
h = 0
for i in 'Python':
    if i == 'h':
        h = 1
        continue
    print(i)
    

P
y
t
o
n


### for else statement 
#### else block is executed once the loop is finished 
#### else block is not executed if break is encountered

In [44]:
for x in range(6):
    print(x)
else :
    print('finished')
    

0
1
2
3
4
5
finished


In [48]:
for i in range(10):
    print(i)
    if i == 5:
        continue
else :
    print('finished')

0
1
2
3
4
5
6
7
8
9
finished


In [50]:
num = int(input('Pls enter a number : '))
for i in range(2, num):
    if num%i == 0 :
        print('non prime')
        break
else : print('Prime')

Pls enter a number :  37


Prime


In [52]:
numbers = [23,45,98,45,32,66,86,77,53, 45]
# create a new list from the abovve list with only odds

In [53]:
odd_number = []
for i in numbers:
    if i %2 != 0:
        odd_number.append(i)
odd_number

[23, 45, 45, 77, 53, 45]

In [57]:
# odd_number = [<iterable> <loop> <condition>]
odd_number = [i**2 for i in numbers if i%2 !=0]
odd_number

[529, 2025, 2025, 5929, 2809, 2025]

### Ex. Write a code to generate a dictionary that contains (i, i*i) such that i is an number between 1 and n (both included). and then the program should print the dictionary.

In [ ]:
{<key : value> < loop > <condition>}

In [58]:
n = 10
{ i : i**2 for i in range(1,n+1)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [61]:
basket

['apple',
 'bananas',
 'potato',
 'broccoli',
 'okra',
 'lettuce',
 'cheese',
 'yogurt',
 'milk']

In [63]:
ht = [1.50,1.55,1.53,1.52,1.57, 1.58]
wt = [55,57.5,54.6, 56.5,55.7,54.7]

In [66]:
BMI = [round( wt[i]/ ht[i]**2, 2) for i in range(len(wt)) ]

In [67]:
BMI

[24.44, 23.93, 23.32, 24.45, 22.6, 21.91]

In [68]:
BMI = [ round(w/h**2, 2) for w,h in zip(wt,ht)]
BMI

[24.44, 23.93, 23.32, 24.45, 22.6, 21.91]

In [72]:
ht = [1.50,1.55,1.53,1.52,1.57, 1.58]
wt = [55,57.5,54.6, 56.5,55.7]

In [73]:
BMI = [ round(w/h**2, 2) for w,h in zip(wt,ht)]
BMI

[24.44, 23.93, 23.32, 24.45, 22.6]

In [71]:
for i,j in zip(wt, ht) :
    print(i,j)
    

55 1.5
57.5 1.55
54.6 1.53
56.5 1.52
55.7 1.57


In [74]:
### Ex. Write a code to create a list of prime numbers between 2000 and 3000
### Ex. write a code to ccreate a list of first 100 prime numbers

In [75]:
'She sells sea shells on the sea shore' #--> remove vowels --> aeiou 

'She sells sea shells on the sea shore'

In [77]:
n = ''
for i in 'She sells sea shells on the sea shore':
    if i.lower() not in 'aeiou':
        n += i # concatenating 
    print(n)
print(n)

S
Sh
Sh
Sh 
Sh s
Sh s
Sh sl
Sh sll
Sh slls
Sh slls 
Sh slls s
Sh slls s
Sh slls s
Sh slls s 
Sh slls s s
Sh slls s sh
Sh slls s sh
Sh slls s shl
Sh slls s shll
Sh slls s shlls
Sh slls s shlls 
Sh slls s shlls 
Sh slls s shlls n
Sh slls s shlls n 
Sh slls s shlls n t
Sh slls s shlls n th
Sh slls s shlls n th
Sh slls s shlls n th 
Sh slls s shlls n th s
Sh slls s shlls n th s
Sh slls s shlls n th s
Sh slls s shlls n th s 
Sh slls s shlls n th s s
Sh slls s shlls n th s sh
Sh slls s shlls n th s sh
Sh slls s shlls n th s shr
Sh slls s shlls n th s shr
Sh slls s shlls n th s shr


## user defined functions 

# reusable code 
len() #

In [ ]:
# function definition :
def function_name (inputs/arguments) :
    statements 1
    statements 2
    statements 3
    return < expression > # optional
# function call
function_name(required inputs)

In [85]:
def isprime(n):
    for i in range(2, n):
        if n%i == 0 :
            print('non prime')
            break
    else : print('Prime')

In [92]:
isprime(37)

Prime


In [90]:
# scope of variables :
num = 34
num

34

In [98]:
def isprime(n):
    print('n = ',n)
    for i in range(2, num):
        print(num , 'is ', end = '')
        if num%i == 0 :
            print('non prime')
            break
    else : print('Prime')

In [99]:
isprime(45)

n =  45
34 is non prime


In [ ]:
# num is a global variable 

In [96]:
num

34

In [97]:
n

'Sh slls s shlls n th s shr'

## argumments
1. positional vs keyword

In [101]:
# which calculates volume of a sphere or cylinder based on the value passed for h 
def volume (r, h):
    if h :
        vol = 3.14 * h * r ** 2
    else :
        vol = 4/3 * 3.14 * r ** 3
    return vol

In [102]:
volume(2,3)

37.68

In [104]:
# r = 3 and h = 2
volume ( h = 2, r =3 )

56.52

2. required vs default 

In [133]:
def volume2 (r, h = None):
    if h :
        return print(3.14 * h * r ** 2 , 'Cylinder')
    else :
        return print(4/3 * 3.14 * r ** 3, 'Sphere')

In [132]:
volume2(5)

523.3333333333334 Sphere


In [120]:
volume2(5, 2)

(157.0, 'Cylinder')

In [125]:
0 == False

True

In [ ]:
if expression --> true / false 

In [126]:
if h :
    
h =0 --> False
h != 0 --> True 


True

In [127]:
h = None

In [130]:
if not h:
    print('none')

none


In [137]:
def volume(r,h = None):
    global vol
    if h:
        vol = 3.14 * h * r ** 2 
    else :
        vol = 4/3 * 3.14 * r ** 3

In [138]:
volume(2,2)

In [139]:
vol

25.12

In [140]:
r

NameError: name 'r' is not defined

In [141]:
def change(b):
    b.append(12)

In [142]:
change(basket)

In [143]:
basket

['apple',
 'bananas',
 'potato',
 'broccoli',
 'okra',
 'lettuce',
 'cheese',
 'yogurt',
 'milk',
 12]

In [144]:
# lambda function 

In [152]:
new_fun = lambda x,y=2 : pow(x,y)

In [154]:
new_fun(5)

25

In [155]:
# exception 

In [156]:
num = int(input ('Please enter a number'))

Please enter a number 32.2


ValueError: invalid literal for int() with base 10: '32.2'

In [159]:
try :
    num = int(input ('Please enter a number'))
except ValueError:
    print('Wrong fromat')  
except :
    print('other problem')
    

Please enter a number 45.6


Wrong fromat


In [162]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

## module 

In [163]:
import numpy as np

In [166]:
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

## Array : homogenous ordered collection of data in 1 or more dimensions

In [169]:
ht = [1.5, 1.55, 1.53, 1.52, 1.57, 1.58]
wt = [55, 57.5, 54.6, 56.5, 55.7, 56.5]

In [179]:
height = np.array(ht)
weight = np.array(wt)

In [172]:
height

array([1.5 , 1.55, 1.53, 1.52, 1.57, 1.58])

In [174]:
l = [1,2,'apple','cream', 4.3, True]
l

[1, 2, 'apple', 'cream', 4.3, True]

In [175]:
np.array([1,2,'apple','cream', 4.3, True])

array(['1', '2', 'apple', 'cream', '4.3', 'True'], dtype='<U21')

In [176]:
np.array(['1',2, 4.3, True])

array(['1', '2', '4.3', 'True'], dtype='<U4')

In [177]:
np.array([1,2, 4.3, True])

array([1. , 2. , 4.3, 1. ])

In [178]:
np.array(['1',2, 4.3, True], dtype = 'int')

array([1, 2, 4, 1])

In [181]:
ht*2

[1.5, 1.55, 1.53, 1.52, 1.57, 1.58, 1.5, 1.55, 1.53, 1.52, 1.57, 1.58]

In [182]:
height * 2

array([3.  , 3.1 , 3.06, 3.04, 3.14, 3.16])

In [183]:
weight/height**2

array([24.44444444, 23.93340271, 23.32436242, 24.45463989, 22.59726561,
       22.63259093])

In [184]:
arr_1d = np.array([23,12,34,56,43])

In [189]:
print(arr_1d.ndim)
print(arr_1d.size)
print(arr_1d.shape)
print(arr_1d.dtype)

1
5
(5,)
int64


In [195]:
arr_2d = np.array([[23, 45, 64],[42, 36, 44],[58, 31, 10]])

In [196]:
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.shape)
print(arr_2d.dtype)

2
9
(3, 3)
int64


In [199]:
np.zeros((2,3), dtype = str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [202]:
np.ones((2,3), dtype = str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [203]:
np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [204]:
np.zeros_like(height)

array([0., 0., 0., 0., 0., 0.])

In [216]:
np.random.rand(2,3,4,5)

array([[[[3.59167946e-01, 5.94616132e-01, 2.39193742e-01,
          4.42500437e-01, 4.92593718e-01],
         [7.93584825e-01, 3.58004324e-01, 2.94718638e-02,
          7.03823103e-01, 5.19667219e-01],
         [6.07898593e-01, 5.93744471e-01, 8.90140059e-01,
          6.13625919e-01, 3.03542646e-01],
         [8.08622318e-01, 7.27951543e-01, 2.89748391e-01,
          3.29576542e-01, 6.38670587e-01]],

        [[7.26796814e-01, 8.18014827e-01, 5.19957287e-01,
          3.08576937e-01, 6.45499428e-01],
         [4.56981128e-01, 1.13340055e-01, 5.16311915e-01,
          8.05130352e-02, 4.21009399e-01],
         [1.51713216e-01, 7.78647556e-01, 7.36731321e-01,
          3.33987303e-01, 4.94855948e-01],
         [9.09208309e-01, 6.62964177e-01, 9.65980717e-01,
          5.28373899e-01, 9.51956435e-01]],

        [[7.56523913e-01, 4.62447951e-01, 2.01433646e-01,
          1.92861612e-01, 3.93631206e-01],
         [2.41632091e-02, 6.77028980e-01, 5.89334376e-01,
          1.95105356e-01, 8.5

In [211]:
np.random.randint(20,50,(2,3))

array([[46, 33, 42],
       [27, 34, 43]])

In [215]:
np.empty((2,3))

array([[0.15159905, 0.43893255, 0.72896627],
       [0.46154849, 0.59836826, 0.83112242]])

In [217]:
arr_2d.shape

(3, 3)

In [218]:
arr_2d

array([[23, 45, 64],
       [42, 36, 44],
       [58, 31, 10]])

In [219]:
# reshaping of an array

In [225]:
arr_2d1 = np.random.randint(10,100,(3,6))

In [232]:
arr_2d1.size

18

In [ ]:
2,9 
9,2
6,3
2,3,3
3,2,3
3,3,2
1 , 18
18 , 1

In [230]:
arr_2d1.reshape(2,9)

array([[66, 21, 51, 36, 49, 48, 93, 99, 41],
       [79, 18, 51, 76, 97, 15, 48, 94, 63]])

In [234]:
arr_3d = arr_2d1.reshape(2,3,3)
arr_3d

array([[[66, 21, 51],
        [36, 49, 48],
        [93, 99, 41]],

       [[79, 18, 51],
        [76, 97, 15],
        [48, 94, 63]]])

In [235]:
arr_2d1

array([[66, 21, 51, 36, 49, 48],
       [93, 99, 41, 79, 18, 51],
       [76, 97, 15, 48, 94, 63]])

In [236]:
arr_2d1.shape = (2,3,3)

In [237]:
arr_2d1

array([[[66, 21, 51],
        [36, 49, 48],
        [93, 99, 41]],

       [[79, 18, 51],
        [76, 97, 15],
        [48, 94, 63]]])